import {CROP_CATALOG,NUTRIENTS,PROBLEMS,ROTATION_FAMILIES,QUICK_ACTIONS} from './data.js';
import {firebaseConfig,firebaseEnabled} from './firebase-config.js';

const $=(s,root=document)=>root.querySelector(s); const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=(d)=>{if(!d)return '—'; const x=new Date(`${d}T12:00:00`);return x.toLocaleDateString('es-ES',{day:'2-digit',month:'short',year:'numeric'})};
const fmtShort=(d)=>{if(!d)return '—'; const x=new Date(`${d}T12:00:00`);return x.toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit'})};
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const addDays=(date,days)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+Number(days||0));return d.toISOString().slice(0,10)};
const diffDays=(a,b=today())=>Math.floor((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000);
const cropInfo=id=>CROP_CATALOG.find(c=>c.id===id) || {id,name:id,icon:'🌿',family:'Otras',ph:[5.5,7.5],calendar:[],plagues:[],diseases:[],deficiencies:[]};

const DEFAULT_STATE=()=>({
 version:1, activeSeason:`Huerto ${new Date().getFullYear()}`,
 seasons:[{id:`season-${new Date().getFullYear()}`,name:`Huerto ${new Date().getFullYear()}`,year:new Date().getFullYear()}],
 visibleCropIds:['potato','tomato','cucumber','pepper','eggplant','zucchini','broadbean','bean','watermelon','melon','strawberry','lettuce'],
 plantings:[], tasks:[], logs:[], zones:[], inventory:[], ph:[], irrigationConfigs:{}, settings:{}, lastSaved:null
});
const LOCAL_KEY='laHuertaAbuela.v1';
let state=loadLocal(); let route='home'; let firebaseCtx=null; let remoteLoading=false; let saveTimer=null;

function loadLocal(){try{const raw=localStorage.getItem(LOCAL_KEY);return raw?{...DEFAULT_STATE(),...JSON.parse(raw)}:DEFAULT_STATE()}catch{return DEFAULT_STATE()}}
function saveLocal(){state.lastSaved=new Date().toISOString();localStorage.setItem(LOCAL_KEY,JSON.stringify(state));if(firebaseCtx?.user && !remoteLoading){clearTimeout(saveTimer);saveTimer=setTimeout(()=>firebaseCtx.save(state),550)}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2400)}
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modalBackdrop').classList.remove('hidden')}
function closeModal(){ $('#modalBackdrop').classList.add('hidden'); }
function seasonObj(){return state.seasons.find(s=>s.name===state.activeSeason) || state.seasons[0]}
function plantingById(id){return state.plantings.find(p=>p.id===id)}
function activePlantings(){return state.plantings.filter(p=>p.season===state.activeSeason && p.status!=='Baja')}
function displayCropName(p){const c=cropInfo(p.cropId);return `${c.icon} ${p.customName||c.name}${p.variety?` · ${p.variety}`:''}`}
function log(type,cropId,summary,details={}){state.logs.unshift({id:uid(),date:today(),createdAt:new Date().toISOString(),type,cropId,season:state.activeSeason,summary,...details});saveLocal()}
function selectOptions(items,getV=x=>x.id,getL=x=>x.name,selected=''){return items.map(x=>`<option value="${esc(getV(x))}" ${getV(x)===selected?'selected':''}>${esc(getL(x))}</option>`).join('')}
function cropSelect(selected='',onlyPlantings=true){const arr=onlyPlantings?activePlantings():state.visibleCropIds.map(id=>({id,cropId:id}));return arr.length?arr.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(onlyPlantings?displayCropName(p):cropInfo(p.cropId).name)}</option>`).join(''):'<option value="">Sin cultivos activos</option>'}

function setRoute(r){route=r;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===r));render()}
function render(){ $('#seasonLabel').textContent=state.activeSeason; $('#todayDate').textContent=new Date().toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'}); const main=$('#mainContent'); if(route==='home')main.innerHTML=renderHome(); if(route==='crops')main.innerHTML=renderCrops(); if(route==='calendar')main.innerHTML=renderCalendar(); if(route==='notebook')main.innerHTML=renderNotebook(); if(route==='more')main.innerHTML=renderMore(); bindPage(); }

function todaysTasks(){return state.tasks.filter(t=>!t.done && t.date===today()).sort((a,b)=>(a.time||'').localeCompare(b.time||''))}
function upcomingTasks(){return state.tasks.filter(t=>!t.done && t.date>today()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,6)}
function activeSafety(){return state.logs.filter(l=>l.type==='Tratamiento' && l.safeHarvestDate && l.safeHarvestDate>today())}
function renderHome(){const tt=todaysTasks(),up=upcomingTasks(),alerts=activeSafety(),recent=state.logs.slice(0,5);
return `<section class="hero-card"><h2>¿Qué toca hoy?</h2><p>${tt.length?`${tt.length} tarea${tt.length>1?'s':''} pendiente${tt.length>1?'s':''}`:'No tienes tareas pendientes para hoy.'}</p><div class="stats-row"><div class="mini-stat"><strong>${activePlantings().length}</strong><span>cultivos</span></div><div class="mini-stat"><strong>${tt.length}</strong><span>hoy</span></div><div class="mini-stat"><strong>${state.logs.length}</strong><span>registros</span></div></div></section>
<section class="section"><div class="section-title"><h2>Accesos rápidos</h2></div><div class="quick-grid">${[['crops','🌱','Cultivos'],['calendar','📅','Calendario'],['irrigation','💧','Riegos'],['fertilization','🌿','Abonados'],['treatment','🧪','Tratamientos'],['tasks','✅','Tareas'],['notebook','📖','Cuaderno'],['harvest','🧺','Cosechas']].map(x=>`<button class="quick-link" data-quick="${x[0]}"><span>${x[1]}</span><small>${x[2]}</small></button>`).join('')}</div></section>
${alerts.length?`<section class="section"><div class="section-title"><h2>⚠️ Avisos importantes</h2></div><div class="list">${alerts.map(a=>`<div class="list-item"><div class="grow"><strong>${esc(a.summary)}</strong><p>No recolectar hasta ${fmtDate(a.safeHarvestDate)}.</p></div><span class="badge danger">Seguridad</span></div>`).join('')}</div></section>`:''}
<section class="section"><div class="section-title"><h2>Tareas de hoy</h2><button data-action="new-task">+ Añadir</button></div>${tt.length?`<div class="list">${tt.map(taskRow).join('')}</div>`:'<div class="empty">No hay tareas para hoy.</div>'}</section>
<section class="section"><div class="section-title"><h2>Próximas tareas</h2></div>${up.length?`<div class="list">${up.map(taskRow).join('')}</div>`:'<div class="empty">Nada programado próximamente.</div>'}</section>
<section class="section"><div class="section-title"><h2>Últimos trabajos</h2><button data-route-jump="notebook">Ver todo</button></div>${recent.length?`<div class="list">${recent.map(logRow).join('')}</div>`:'<div class="empty">Tu cuaderno todavía está vacío.</div>'}</section>
<section class="section"><div class="section-title"><h2>Mis cultivos</h2><button data-route-jump="crops">Gestionar</button></div><div class="crop-grid">${state.visibleCropIds.slice(0,12).map(cropButton).join('')}<button class="crop-btn add-crop" data-action="add-crop"><span class="emoji">＋</span><strong>Añadir cultivo</strong></button></div></section>`}

function taskRow(t){const p=plantingById(t.plantingId);return `<div class="list-item"><button class="icon-btn" style="width:40px;height:40px" data-complete-task="${t.id}">○</button><div class="grow"><strong>${esc(t.title)}</strong><p>${p?displayCropName(p)+' · ':''}${fmtDate(t.date)}${t.time?' · '+esc(t.time):''}</p></div><button class="icon-btn" style="width:38px;height:38px" data-edit-task="${t.id}">⋯</button></div>`}
function logRow(l){const icons={Riego:'💧',Abonado:'🌱',Tratamiento:'🧪',Cosecha:'🧺',pH:'🧫',Observación:'📝',Siembra:'🌱',Trasplante:'🌿',Poda:'✂️',Aporcado:'⛰️',Laboreo:'🚜',Tarea:'✅'};const c=l.cropId?cropInfo(l.cropId):null;return `<div class="list-item"><div style="font-size:1.35rem">${icons[l.type]||'📌'}</div><div class="grow"><strong>${c?`${c.icon} `:''}${esc(l.summary)}</strong><p>${fmtDate(l.date)}${l.notes?' · '+esc(l.notes):''}</p></div><span class="badge">${esc(l.type)}</span></div>`}
function cropButton(id){const c=cropInfo(id);const count=activePlantings().filter(p=>p.cropId===id).length;return `<button class="crop-btn" data-crop="${id}"><span class="emoji">${c.icon}</span><strong>${esc(c.name)}</strong>${count?`<small>${count} plantación${count>1?'es':''}</small>`:''}</button>`}

function renderCrops(){return `<section class="section"><div class="section-title"><h2>Cultivos visibles</h2><button data-action="manage-visible">Ocultar/mostrar</button></div><div class="crop-grid">${state.visibleCropIds.map(cropButton).join('')}<button class="crop-btn add-crop" data-action="add-crop"><span class="emoji">＋</span><strong>Añadir cultivo</strong></button></div></section>
<section class="section"><div class="section-title"><h2>Plantaciones de ${esc(state.activeSeason)}</h2><button data-action="new-planting">+ Nueva</button></div>${activePlantings().length?`<div class="list">${activePlantings().map(p=>`<button class="list-item" style="width:100%;text-align:left" data-planting="${p.id}"><div style="font-size:1.7rem">${cropInfo(p.cropId).icon}</div><div class="grow"><strong>${esc(p.customName||cropInfo(p.cropId).name)}${p.variety?' · '+esc(p.variety):''}</strong><p>${p.zoneId?esc(state.zones.find(z=>z.id===p.zoneId)?.name||'')+' · ':''}${p.transplantDate?`Trasplante ${fmtDate(p.transplantDate)}`:p.sowDate?`Siembra ${fmtDate(p.sowDate)}`:'Sin fecha de inicio'}</p></div><span class="badge">${esc(p.status||'Activo')}</span></button>`).join('')}</div>`:'<div class="empty">Aún no has creado ninguna plantación esta temporada.</div>'}</section>`}

function autoCalendarEvents(){let out=[];for(const p of activePlantings()){const c=cropInfo(p.cropId), base=p.transplantDate||p.sowDate;if(!base)continue;(c.calendar||[]).forEach(([name,offset])=>out.push({id:`auto-${p.id}-${name}`,date:addDays(base,offset),title:name,plantingId:p.id,auto:true,cropId:p.cropId}))} return out;}
function renderCalendar(){const events=[...autoCalendarEvents(),...state.tasks.filter(t=>!t.done).map(t=>({...t,cropId:plantingById(t.plantingId)?.cropId}))].sort((a,b)=>a.date.localeCompare(b.date)).filter(e=>e.date>=addDays(today(),-7)).slice(0,60);return `<section class="section"><div class="section-title"><h2>Calendario y tareas</h2><button data-action="new-task">+ Evento</button></div><div class="warning-box">Las fechas automáticas son orientativas y se calculan desde la siembra o el trasplante. Puedes crear tareas con fechas reales para sustituirlas en tu planificación.</div></section><section class="section"><div class="timeline">${events.length?events.map(e=>{const p=plantingById(e.plantingId);return `<div class="timeline-item"><strong>${fmtDate(e.date)} · ${esc(e.title)}</strong><small>${p?' '+displayCropName(p):''}${e.auto?' · fecha orientativa':''}</small></div>`}).join(''):'<div class="empty">No hay fechas próximas.</div>'}</div></section>`}

function renderNotebook(){return `<section class="section"><div class="section-title"><h2>Cuaderno de campo</h2><button data-action="export-csv">CSV</button></div><div class="form-grid"><div class="field"><label>Filtrar cultivo</label><select id="notebookCrop"><option value="">Todos</option>${CROP_CATALOG.map(c=>`<option value="${c.id}">${c.icon} ${c.name}</option>`).join('')}</select></div><div class="field"><label>Tipo</label><select id="notebookType"><option value="">Todos</option>${['Riego','Siembra','Trasplante','Abonado','Tratamiento','Poda','Aporcado','Laboreo','Cosecha','Observación','pH','Tarea'].map(x=>`<option>${x}</option>`).join('')}</select></div></div></section><section class="section"><div id="notebookList" class="list">${state.logs.length?state.logs.map(logRow).join(''):'<div class="empty">No hay registros todavía.</div>'}</div></section>`}

function renderMore(){const online=navigator.onLine;const authText=!firebaseEnabled?'Firebase pendiente de configurar.':firebaseCtx?.user?`Conectado como ${firebaseCtx.user.email}`:firebaseCtx?'Sin iniciar sesión. Los datos se guardan solo en este dispositivo.':'Preparando Firebase…';return `<section class="section"><div class="card"><strong><span class="status-dot ${online?'online':'offline'}"></span>${online?'Con conexión':'Sin conexión'}</strong><p class="help">Los datos se guardan localmente. Con Firebase configurado, Firestore sincroniza al recuperar conexión.</p><div id="authStatus" class="help">${esc(authText)}</div></div></section>
<section class="section"><div class="more-grid">${[
['tasks','✅','Tareas','Planifica y completa trabajos'],['zones','🗺️','Zonas','Rotación, pH e historial'],['inventory','📦','Mi almacén','Fertilizantes, fitosanitarios y semillas'],['ph','🧫','pH del suelo','Mediciones por zona y cultivo'],['dose','🧮','Calculadora','Dosificaciones y mezclas'],['harvests','🧺','Cosechas','Producción por cultivo'],['problems','🐛','Problemas','Plagas, enfermedades y carencias'],['search','🔎','Buscador','Síntomas, fichas y registros'],['seasons','🗓️','Temporadas','Cambiar de campaña'],['backup','💾','Copias','Exportar/importar JSON y CSV'],['auth','👤','Cuenta','Inicio de sesión y sincronización'],['about','ℹ️','Información','Uso seguro de datos agronómicos']
].map(x=>`<button class="more-card" data-more="${x[0]}"><span>${x[1]}</span><strong>${x[2]}</strong><small>${x[3]}</small></button>`).join('')}</div></section>`}

function bindPage(){
 $$('[data-route-jump]').forEach(b=>b.onclick=()=>setRoute(b.dataset.routeJump));
 $$('[data-crop]').forEach(b=>b.onclick=()=>openCropCatalog(b.dataset.crop));
 $$('[data-planting]').forEach(b=>b.onclick=()=>openPlanting(b.dataset.planting));
 $$('[data-action="add-crop"],[data-action="new-planting"]').forEach(b=>b.onclick=()=>openPlantingForm());
 $$('[data-action="manage-visible"]').forEach(b=>b.onclick=manageVisibleCrops);
 $$('[data-action="new-task"]').forEach(b=>b.onclick=()=>openTaskForm());
 $$('[data-complete-task]').forEach(b=>b.onclick=()=>completeTask(b.dataset.completeTask));
 $$('[data-edit-task]').forEach(b=>b.onclick=()=>editTaskMenu(b.dataset.editTask));
 $$('[data-quick]').forEach(b=>b.onclick=()=>handleQuick(b.dataset.quick));
 $$('[data-more]').forEach(b=>b.onclick=()=>openMore(b.dataset.more));
 $('#notebookCrop')?.addEventListener('change',filterNotebook); $('#notebookType')?.addEventListener('change',filterNotebook);
}
function filterNotebook(){const c=$('#notebookCrop').value,t=$('#notebookType').value;const arr=state.logs.filter(l=>(!c||l.cropId===c)&&(!t||l.type===t));$('#notebookList').innerHTML=arr.length?arr.map(logRow).join(''):'<div class="empty">No hay resultados.</div>'}

function openCropCatalog(id){const c=cropInfo(id),p=activePlantings().filter(x=>x.cropId===id);modal(`${c.icon} ${c.name}`,`<div class="crop-hero"><div class="emoji">${c.icon}</div><div><h2>${c.name}</h2><p>${c.family} · pH ${c.ph[0]}–${c.ph[1]}</p></div></div>${p.length?`<div class="section"><h3>Mis plantaciones</h3><div class="list">${p.map(x=>`<button class="list-item" data-open-p="${x.id}" style="width:100%;text-align:left"><div class="grow"><strong>${esc(x.variety||'Sin variedad')}</strong><p>${x.zoneId?esc(state.zones.find(z=>z.id===x.zoneId)?.name||''):'Sin zona'}</p></div></button>`).join('')}</div></div>`:''}<div class="actions"><button class="btn primary block" id="newPlantingFromCrop">+ Nueva plantación</button></div>${cropGuide(c)}`);$('#newPlantingFromCrop').onclick=()=>openPlantingForm(null,id);$$('[data-open-p]').forEach(b=>b.onclick=()=>openPlanting(b.dataset.openP))}
function cropGuide(c){return `<section class="section"><div class="section-title"><h2>Guía práctica</h2></div><div class="detail-grid">${[['Siembra',c.planting],['Temperatura',`${c.temp?.[0]||'—'} / ${c.temp?.[1]||'—'} / ${c.temp?.[2]||'—'} °C`],['Marco',c.spacing],['Profundidad',c.depth],['Sol',c.sun],['Suelo',c.soil],['pH recomendado',`${c.ph[0]}–${c.ph[1]}`],['Duración',`${c.days||'—'} días aprox.`]].map(([a,b])=>`<div class="detail"><span>${a}</span><strong>${esc(b||'—')}</strong></div>`).join('')}</div><div class="card" style="margin-top:10px"><strong>💧 Riego</strong><p>${esc(c.water||'')}</p><strong>🌱 Fertilización</strong><p>${esc(c.fert||'')}</p><strong>🧺 Recolección</strong><p>${esc(c.harvest||'')} · ${esc(c.yield||'')}</p><strong>🐛 Problemas habituales</strong><p>${esc([...(c.plagues||[]),...(c.diseases||[])].join(', '))}</p><strong>⚠️ Carencias frecuentes</strong><p>${esc((c.deficiencies||[]).join(', '))}</p></div><div class="card" style="margin-top:10px"><strong>Funciones de los nutrientes</strong>${NUTRIENTS.map(n=>`<p><b>${esc(n[0])}:</b> ${esc(n[1])}</p>`).join('')}</div></section>`}

function openPlanting(id){const p=plantingById(id);if(!p)return;const c=cropInfo(p.cropId),base=p.transplantDate||p.sowDate,days=base?diffDays(base):null,lastIrr=state.logs.find(l=>l.type==='Riego'&&l.plantingId===p.id),lastF=state.logs.find(l=>l.type==='Abonado'&&l.plantingId===p.id),phLast=state.ph.filter(x=>x.plantingId===p.id || (p.zoneId&&x.zoneId===p.zoneId)).sort((a,b)=>b.date.localeCompare(a.date))[0];
modal(displayCropName(p),`<div class="crop-hero"><div class="emoji">${c.icon}</div><div><h2>${esc(p.variety||c.name)}</h2><p>${p.zoneId?esc(state.zones.find(z=>z.id===p.zoneId)?.name||'Sin zona'):'Sin zona'} · ${esc(p.status||'Activo')}${days!==null?` · ${days} días`:''}</p></div></div><div class="detail-grid">${[['Siembra',fmtDate(p.sowDate)],['Trasplante',fmtDate(p.transplantDate)],['Plantas',p.plants||'—'],['Superficie',p.area?`${p.area} m²`:'—'],['Marco',p.spacing||c.spacing||'—'],['Último riego',lastIrr?fmtDate(lastIrr.date):'—'],['Último abonado',lastF?fmtDate(lastF.date):'—'],['pH actual',phLast?phLast.value:'—']].map(([a,b])=>`<div class="detail"><span>${a}</span><strong>${esc(b)}</strong></div>`).join('')}</div>
<div class="action-grid">${[['irrigation','💧 Riego'],['calendar','📅 Calendario'],['fertilization','🌱 Abonado'],['problems','🐛 Plagas'],['problems','🦠 Enfermedades'],['treatment','🧪 Tratamientos'],['observation','✂️ Trabajos'],['harvest','🧺 Cosecha'],['guide','📖 Información'],['history','📝 Historial']].map(x=>`<button class="big-action" data-pa="${x[0]}"><span>${x[1].split(' ')[0]}</span>${x[1].split(' ').slice(1).join(' ')}</button>`).join('')}</div>
<div class="actions"><button class="btn secondary" id="editPlanting">Editar ficha</button><button class="btn danger" id="closePlanting">Dar de baja</button></div>`);
$$('[data-pa]').forEach(b=>b.onclick=()=>plantingAction(b.dataset.pa,p));$('#editPlanting').onclick=()=>openPlantingForm(p.id);$('#closePlanting').onclick=()=>{p.status='Baja';log('Observación',p.cropId,`${c.name}: plantación dada de baja`,{plantingId:p.id});saveLocal();closeModal();render()};}
function plantingAction(a,p){if(a==='irrigation')openIrrigationForm(p.id);else if(a==='fertilization')openFertilizationForm(p.id);else if(a==='treatment')openTreatmentForm(p.id);else if(a==='harvest')openHarvestForm(p.id);else if(a==='observation')openObservationForm(p.id);else if(a==='problems')openProblems(p.cropId);else if(a==='guide')openCropCatalog(p.cropId);else if(a==='history')openHistory(p);else if(a==='calendar')openCropCalendar(p)}
function openHistory(p){const rows=state.logs.filter(l=>l.plantingId===p.id);modal(`Historial · ${displayCropName(p)}`,rows.length?`<div class="list">${rows.map(logRow).join('')}</div>`:'<div class="empty">Sin registros.</div>')}
function openCropCalendar(p){const c=cropInfo(p.cropId),base=p.transplantDate||p.sowDate;if(!base)return toast('Añade primero una fecha de siembra o trasplante.');const rows=(c.calendar||[]).map(([n,o])=>({n,date:addDays(base,o)}));modal(`Calendario · ${c.name}`,`<div class="warning-box">Calendario orientativo calculado desde ${fmtDate(base)}.</div><div class="timeline" style="margin-top:15px">${rows.map(x=>`<div class="timeline-item"><strong>${fmtDate(x.date)} · ${esc(x.n)}</strong></div>`).join('')}</div><button class="btn primary block" id="addCropTask">+ Crear evento real</button>`);$('#addCropTask').onclick=()=>openTaskForm(null,p.id)}

function openPlantingForm(id=null,presetCrop=null){const p=id?plantingById(id):null;modal(p?'Editar plantación':'Nueva plantación',`<form id="plantingForm" class="form-grid"><div class="field full"><label>Cultivo</label><select name="cropId">${CROP_CATALOG.map(c=>`<option value="${c.id}" ${(p?.cropId||presetCrop)===c.id?'selected':''}>${c.icon} ${c.name}</option>`).join('')}</select></div><div class="field"><label>Variedad</label><input name="variety" value="${esc(p?.variety||'')}" placeholder="Huevo de Toro"></div><div class="field"><label>Estado</label><select name="status">${['Activo','Semillero','Finalizando','Baja'].map(x=>`<option ${p?.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Fecha siembra</label><input type="date" name="sowDate" value="${p?.sowDate||''}"></div><div class="field"><label>Fecha trasplante</label><input type="date" name="transplantDate" value="${p?.transplantDate||''}"></div><div class="field"><label>Nº plantas</label><input type="number" min="0" name="plants" value="${p?.plants||''}"></div><div class="field"><label>Superficie m²</label><input type="number" step="0.1" min="0" name="area" value="${p?.area||''}"></div><div class="field"><label>Marco plantación</label><input name="spacing" value="${esc(p?.spacing||'')}"></div><div class="field"><label>Zona</label><select name="zoneId"><option value="">Sin zona</option>${selectOptions(state.zones,z=>z.id,z=>z.name,p?.zoneId||'')}</select></div><div class="field full"><label>Observaciones</label><textarea name="notes">${esc(p?.notes||'')}</textarea></div><div class="field full"><button class="btn primary block">Guardar plantación</button></div></form>`);$('#plantingForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(p)Object.assign(p,d,{plants:Number(d.plants)||null,area:Number(d.area)||null});else{const np={id:uid(),...d,plants:Number(d.plants)||null,area:Number(d.area)||null,season:state.activeSeason,createdAt:new Date().toISOString()};state.plantings.push(np);if(!state.visibleCropIds.includes(d.cropId))state.visibleCropIds.push(d.cropId);log(d.transplantDate?'Trasplante':'Siembra',d.cropId,`${cropInfo(d.cropId).name}${d.variety?' · '+d.variety:''}`,{plantingId:np.id,date:d.transplantDate||d.sowDate||today(),notes:d.notes})}saveLocal();closeModal();render();toast('Plantación guardada')}}
function manageVisibleCrops(){modal('Cultivos visibles',`<p class="help">Marca solo los cultivos que quieres tener a mano en la cuadrícula principal.</p><form id="visibleForm" class="list">${CROP_CATALOG.map(c=>`<label class="list-item"><input type="checkbox" name="crops" value="${c.id}" ${state.visibleCropIds.includes(c.id)?'checked':''}><div class="grow"><strong>${c.icon} ${c.name}</strong><p>${c.family}</p></div></label>`).join('')}<button class="btn primary">Guardar</button></form>`);$('#visibleForm').onsubmit=e=>{e.preventDefault();state.visibleCropIds=[...new FormData(e.target).getAll('crops')];saveLocal();closeModal();render()}}

function openQuickMenu(){modal('Registrar rápido',`<div class="action-grid">${QUICK_ACTIONS.map(([a,i,l])=>`<button class="big-action" data-qa="${a}"><span>${i}</span>${l}</button>`).join('')}</div>`);$$('[data-qa]').forEach(b=>b.onclick=()=>handleQuick(b.dataset.qa))}
function handleQuick(a){if(a==='crops')return setRoute('crops');if(a==='calendar')return setRoute('calendar');if(a==='notebook')return setRoute('notebook');if(a==='irrigation')return openIrrigationForm();if(a==='fertilization')return openFertilizationForm();if(a==='treatment')return openTreatmentForm();if(a==='harvest')return openHarvestForm();if(a==='task'||a==='tasks')return openTaskForm();if(a==='observation')return openObservationForm();if(a==='crop')return openPlantingForm();if(a==='ph')return openPhForm()}

function openIrrigationForm(plantingId=''){if(!activePlantings().length)return toast('Crea primero una plantación.');const p=plantingById(plantingId)||activePlantings()[0],cfg=state.irrigationConfigs[p.id]||{};modal('💧 Registrar riego',`<form id="irrigationForm" class="form-grid"><div class="field full"><label>Cultivo</label><select name="plantingId" id="irrPlanting">${cropSelect(p.id)}</select></div><div class="field"><label>Estado del riego</label><select name="level"><option>No regar</option><option selected>Riego normal</option><option>Riego reducido</option><option>Riego abundante</option></select></div><div class="field"><label>Duración (min)</label><input type="number" min="0" step="1" name="minutes" value="${cfg.lastMinutes||''}"></div><div class="field"><label>Caudal total (L/h)</label><input type="number" min="0" step="0.1" name="flow" id="irrFlow" value="${cfg.flow||''}"></div><div class="field"><label>Superficie regada (m²)</label><input type="number" min="0" step="0.1" name="area" id="irrArea" value="${cfg.area||p.area||''}"></div><div class="field"><label>Objetivo (L/m²)</label><input type="number" min="0" step="0.1" name="target" id="irrTarget" value="${cfg.target||''}"></div><div class="field"><label>Nº goteros</label><input type="number" min="0" name="emitters" id="irrEmitters" value="${cfg.emitters||''}"></div><div class="field"><label>Separación goteros (cm)</label><input type="number" min="0" step="1" name="emitterSpacing" value="${cfg.emitterSpacing||''}"></div><div class="field"><label>Caudal/gotero (L/h)</label><input type="number" min="0" step="0.1" name="emitterFlow" id="irrEmitterFlow" value="${cfg.emitterFlow||''}"></div><div class="field full"><div id="irrCalc" class="calc-result">Introduce caudal, superficie y objetivo para calcular el tiempo.</div></div><div class="field full"><label>Observaciones</label><textarea name="notes"></textarea></div><div class="field full"><button class="btn primary block">Guardar riego</button></div></form>`);
const recalc=()=>{let flow=Number($('#irrFlow').value)||0,area=Number($('#irrArea').value)||0,target=Number($('#irrTarget').value)||0,em=Number($('#irrEmitters').value)||0,ef=Number($('#irrEmitterFlow').value)||0;if(!flow&&em&&ef){flow=em*ef;$('#irrFlow').value=flow.toFixed(1)}const rate=flow&&area?flow/area:0,hrs=rate&&target?target/rate:0;$('#irrCalc').innerHTML=rate?`La instalación aporta <b>${rate.toFixed(1)} L/m²/h</b>. ${target?`Para aplicar <b>${target} L/m²</b>: <b>${Math.round(hrs*60)} min</b>.`:''}`:'Introduce los datos de la instalación.'};$$('#irrigationForm input').forEach(i=>i.oninput=recalc);recalc();
$('#irrPlanting').onchange=()=>{const np=plantingById($('#irrPlanting').value),ncfg=state.irrigationConfigs[np.id]||{};$('#irrFlow').value=ncfg.flow||'';$('#irrArea').value=ncfg.area||np.area||'';$('#irrTarget').value=ncfg.target||'';$('#irrEmitters').value=ncfg.emitters||'';$('#irrEmitterFlow').value=ncfg.emitterFlow||'';recalc()};
$('#irrigationForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),pp=plantingById(d.plantingId),flow=Number(d.flow)||0,minutes=Number(d.minutes)||0,area=Number(d.area)||0,liters=flow*minutes/60;state.irrigationConfigs[pp.id]={flow,area,target:Number(d.target)||null,emitters:Number(d.emitters)||null,emitterSpacing:Number(d.emitterSpacing)||null,emitterFlow:Number(d.emitterFlow)||null,lastMinutes:minutes};log('Riego',pp.cropId,`${cropInfo(pp.cropId).name} — ${minutes} min`,{plantingId:pp.id,minutes,liters:Number(liters.toFixed(1)),area,level:d.level,notes:d.notes});saveLocal();closeModal();render();toast(`Riego guardado${liters?` · ${liters.toFixed(0)} L aprox.`:''}`)}}

function inventoryOptions(typeFilter=''){const arr=state.inventory.filter(x=>!typeFilter||x.category===typeFilter);return `<option value="">Sin producto del almacén</option>${arr.map(x=>`<option value="${x.id}">${esc(x.name)} · ${x.quantity||0} ${esc(x.unit||'')}</option>`).join('')}`}
function openFertilizationForm(plantingId=''){if(!activePlantings().length)return toast('Crea primero una plantación.');const p=plantingById(plantingId)||activePlantings()[0];modal('🌱 Registrar abonado',`<form id="fertForm" class="form-grid"><div class="field full"><label>Cultivo</label><select name="plantingId">${cropSelect(p.id)}</select></div><div class="field full"><label>Producto del almacén</label><select name="productId">${inventoryOptions('Fertilizantes')}</select></div><div class="field"><label>Producto / nombre</label><input name="product" placeholder="Potasa, NPK..."></div><div class="field"><label>Forma aplicación</label><select name="method"><option>Fertirriego</option><option>Riego manual</option><option>Foliar</option><option>Suelo</option><option>Incorporado</option></select></div><div class="field"><label>Dosis producto</label><input type="number" step="0.01" name="dose" id="fertDose" placeholder="2"></div><div class="field"><label>Por cada litros de agua</label><input type="number" step="1" name="doseWater" id="fertDoseWater" value="1000"></div><div class="field"><label>Agua a preparar (L)</label><input type="number" step="1" name="water" id="fertWater" placeholder="400"></div><div class="field"><label>Cantidad usada</label><input type="number" step="0.01" name="amount" id="fertAmount"></div><div class="field full"><div id="fertCalc" class="calc-result">Ejemplo: 2 L / 1.000 L y una cuba de 400 L = 0,8 L de producto.</div></div><div class="field full"><label>Unidad del producto</label><select name="unit"><option>L</option><option>ml</option><option>kg</option><option>g</option></select></div><div class="field full"><label>Observaciones</label><textarea name="notes"></textarea></div><div class="field full"><button class="btn primary block">Guardar abonado</button></div></form>`);const calc=()=>{const dose=Number($('#fertDose').value),dw=Number($('#fertDoseWater').value),w=Number($('#fertWater').value);if(dose&&dw&&w){const a=dose*w/dw;$('#fertAmount').value=+a.toFixed(3);$('#fertCalc').innerHTML=`Necesitas <b>${a.toFixed(3)}</b> unidades de producto para ${w} L.`}};['#fertDose','#fertDoseWater','#fertWater'].forEach(s=>$(s).oninput=calc);$('#fertForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),pp=plantingById(d.plantingId),inv=state.inventory.find(x=>x.id===d.productId),product=d.product||inv?.name||'Abonado';const amount=Number(d.amount)||0;if(inv&&amount){inv.quantity=Math.max(0,(Number(inv.quantity)||0)-amount)}log('Abonado',pp.cropId,`${cropInfo(pp.cropId).name} — ${product}`,{plantingId:pp.id,product,amount,unit:d.unit,water:Number(d.water)||null,method:d.method,notes:d.notes});saveLocal();closeModal();render();toast('Abonado guardado')}}

function openTreatmentForm(plantingId=''){if(!activePlantings().length)return toast('Crea primero una plantación.');const p=plantingById(plantingId)||activePlantings()[0];modal('🧪 Nuevo tratamiento',`<div class="danger-box">La app no propone dosis, materias activas ni plazos legales. Introduce exactamente los datos de la etiqueta del producto autorizado para ese cultivo y uso.</div><form id="treatForm" class="form-grid" style="margin-top:12px"><div class="field full"><label>Cultivo</label><select name="plantingId">${cropSelect(p.id)}</select></div><div class="field"><label>Objetivo</label><input name="target" placeholder="Araña roja"></div><div class="field full"><label>Producto del almacén</label><select name="productId">${inventoryOptions('Fitosanitarios')}</select></div><div class="field"><label>Producto</label><input name="product" placeholder="Nombre de etiqueta"></div><div class="field"><label>Materia activa</label><input name="active"></div><div class="field"><label>Dosis (texto etiqueta)</label><input name="dose" placeholder="Ej. 4 g/L"></div><div class="field"><label>Litros utilizados</label><input type="number" step="0.1" name="water"></div><div class="field"><label>Zona</label><input name="zone"></div><div class="field"><label>Plazo seguridad (días)</label><input type="number" min="0" name="safetyDays" value="0"></div><div class="field"><label>Cantidad descontada almacén</label><input type="number" min="0" step="0.01" name="inventoryAmount" placeholder="Opcional"></div><div class="field full"><label>Observaciones</label><textarea name="notes"></textarea></div><div class="field full"><button class="btn primary block">Guardar tratamiento</button></div></form>`);$('#treatForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),pp=plantingById(d.plantingId),inv=state.inventory.find(x=>x.id===d.productId),product=d.product||inv?.name||'Tratamiento',used=Number(d.inventoryAmount)||0,sd=Number(d.safetyDays)||0,safe=sd?addDays(today(),sd):null;if(inv&&used)inv.quantity=Math.max(0,(Number(inv.quantity)||0)-used);log('Tratamiento',pp.cropId,`${cropInfo(pp.cropId).name} — ${product}${d.target?' contra '+d.target:''}`,{plantingId:pp.id,product,target:d.target,active:d.active,dose:d.dose,water:Number(d.water)||null,zone:d.zone,safetyDays:sd,safeHarvestDate:safe,inventoryAmount:used,notes:d.notes});saveLocal();closeModal();render();toast(safe?`Guardado · recolectar desde ${fmtDate(safe)}`:'Tratamiento guardado')}}
function openHarvestForm(plantingId=''){if(!activePlantings().length)return toast('Crea primero una plantación.');const p=plantingById(plantingId)||activePlantings()[0];modal('🧺 Registrar cosecha',`<form id="harvestForm" class="form-grid"><div class="field full"><label>Cultivo</label><select name="plantingId">${cropSelect(p.id)}</select></div><div class="field"><label>Fecha</label><input type="date" name="date" value="${today()}"></div><div class="field"><label>Kilogramos</label><input type="number" step="0.01" min="0" name="kg" required></div><div class="field"><label>Calidad</label><select name="quality"><option>Muy buena</option><option selected>Buena</option><option>Regular</option><option>Descarte</option></select></div><div class="field full"><label>Observaciones</label><textarea name="notes"></textarea></div><div class="field full"><button class="btn primary block">Guardar cosecha</button></div></form>`);$('#harvestForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),pp=plantingById(d.plantingId),kg=Number(d.kg);log('Cosecha',pp.cropId,`${cropInfo(pp.cropId).name} — ${kg} kg`,{plantingId:pp.id,date:d.date,kg,quality:d.quality,notes:d.notes});saveLocal();closeModal();render();toast('Cosecha guardada')}}
function openObservationForm(plantingId=''){const p=plantingById(plantingId)||activePlantings()[0];modal('📝 Añadir trabajo/observación',`<form id="obsForm" class="form-grid"><div class="field full"><label>Cultivo</label><select name="plantingId"><option value="">General</option>${cropSelect(p?.id||'')}</select></div><div class="field"><label>Tipo</label><select name="type">${['Observación','Poda','Aporcado','Laboreo','Siembra','Trasplante','Otros'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Fecha</label><input type="date" name="date" value="${today()}"></div><div class="field full"><label>Qué has hecho / observado</label><textarea name="notes" required></textarea></div><div class="field full"><button class="btn primary block">Guardar</button></div></form>`);$('#obsForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),pp=plantingById(d.plantingId);log(d.type,pp?.cropId||null,d.notes,{plantingId:pp?.id||null,date:d.date,notes:''});saveLocal();closeModal();render();toast('Registro guardado')}}

function openTaskForm(taskId=null,plantingId=''){const t=state.tasks.find(x=>x.id===taskId);modal(t?'Editar tarea':'Nueva tarea',`<form id="taskForm" class="form-grid"><div class="field full"><label>Tarea</label><input name="title" required value="${esc(t?.title||'')}"></div><div class="field"><label>Fecha</label><input type="date" name="date" value="${t?.date||today()}" required></div><div class="field"><label>Hora opcional</label><input type="time" name="time" value="${t?.time||''}"></div><div class="field full"><label>Cultivo</label><select name="plantingId"><option value="">General</option>${cropSelect(t?.plantingId||plantingId)}</select></div><div class="field full"><label>Notas</label><textarea name="notes">${esc(t?.notes||'')}</textarea></div><div class="field full"><button class="btn primary block">Guardar tarea</button></div></form>`);$('#taskForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(t)Object.assign(t,d);else state.tasks.push({id:uid(),...d,done:false,season:state.activeSeason,createdAt:new Date().toISOString()});saveLocal();closeModal();render();toast('Tarea guardada')}}
function completeTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.done=true;t.doneAt=new Date().toISOString();const p=plantingById(t.plantingId);log('Tarea',p?.cropId||null,t.title,{plantingId:p?.id||null,notes:t.notes});saveLocal();render();toast('Tarea completada y añadida al cuaderno')}
function editTaskMenu(id){const t=state.tasks.find(x=>x.id===id);modal('Tarea',`<div class="card"><strong>${esc(t.title)}</strong><p>${fmtDate(t.date)}</p></div><div class="actions"><button class="btn primary" id="editTaskBtn">Editar</button><button class="btn secondary" id="postponeTask">Posponer 1 día</button><button class="btn danger" id="deleteTask">Eliminar</button></div>`);$('#editTaskBtn').onclick=()=>openTaskForm(id);$('#postponeTask').onclick=()=>{t.date=addDays(t.date,1);saveLocal();closeModal();render()};$('#deleteTask').onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==id);saveLocal();closeModal();render()}}

function openPhForm(){modal('🧫 Registrar pH',`<form id="phForm" class="form-grid"><div class="field"><label>Fecha</label><input type="date" name="date" value="${today()}"></div><div class="field"><label>pH medido</label><input type="number" min="0" max="14" step="0.01" name="value" required></div><div class="field"><label>Zona</label><select name="zoneId"><option value="">Sin zona</option>${selectOptions(state.zones,z=>z.id,z=>z.name)}</select></div><div class="field"><label>Cultivo</label><select name="plantingId"><option value="">Sin cultivo</option>${cropSelect()}</select></div><div class="field full"><label>Método</label><input name="method" placeholder="Medidor digital, extracto 1:2..."></div><div class="field full"><label>Observaciones</label><textarea name="notes"></textarea></div><div class="field full"><button class="btn primary block">Guardar medición</button></div></form>`);$('#phForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),p=plantingById(d.plantingId),v=Number(d.value);state.ph.unshift({id:uid(),...d,value:v,cropId:p?.cropId||null,season:state.activeSeason});let msg='pH guardado';if(p){const c=cropInfo(p.cropId);if(v<c.ph[0])msg+=` · bajo para ${c.name}`;if(v>c.ph[1])msg+=` · alto para ${c.name}`}log('pH',p?.cropId||null,`pH ${v}`,{plantingId:p?.id||null,date:d.date,notes:d.notes});saveLocal();closeModal();render();toast(msg)}}

function openProblems(cropId=''){const c=cropId?cropInfo(cropId):null,related=PROBLEMS.filter(x=>!c || [...c.plagues,...c.diseases,...c.deficiencies].some(n=>n.toLowerCase().includes(x.name.toLowerCase())||x.name.toLowerCase().includes(n.toLowerCase())));modal('🐛 Plagas, enfermedades y carencias',`<div class="warning-box">El buscador por síntomas ofrece orientación, no un diagnóstico seguro. Confirma la causa antes de tratar.</div><div class="search-box" style="margin-top:10px"><input id="symptomSearch" placeholder="Ej. hojas amarillas, telarañas"><button class="btn primary" id="symptomBtn">Buscar</button></div><div id="problemList" class="list" style="margin-top:12px">${problemCards(related.length?related:PROBLEMS)}</div>`);$('#symptomBtn').onclick=()=>{const q=$('#symptomSearch').value.toLowerCase().trim();const words=q.split(/\s+/).filter(Boolean);const arr=PROBLEMS.map(p=>({p,score:words.reduce((s,w)=>s+([p.name,p.type,p.identify,p.favours,...p.symptoms].join(' ').toLowerCase().includes(w)?1:0),0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score).map(x=>x.p);$('#problemList').innerHTML=arr.length?problemCards(arr):'<div class="empty">No encuentro coincidencias claras. Revisa síntomas y evita tratar a ciegas.</div>';bindProblemCards()};bindProblemCards()}
function problemCards(arr){return arr.map((p,i)=>`<button class="list-item" style="width:100%;text-align:left" data-problem="${esc(p.name)}"><div class="grow"><strong>${esc(p.name)}</strong><p>${esc(p.type)} · ${esc(p.symptoms.slice(0,3).join(', '))}</p></div><span class="badge">Ver</span></button>`).join('')}
function bindProblemCards(){$$('[data-problem]').forEach(b=>b.onclick=()=>{const p=PROBLEMS.find(x=>x.name===b.dataset.problem);modal(p.name,`<div class="badge">${p.type}</div><section class="section"><div class="card"><strong>Síntomas</strong><p>${esc(p.symptoms.join(', '))}</p><strong>Cómo identificarlo</strong><p>${esc(p.identify)}</p><strong>Condiciones favorables</strong><p>${esc(p.favours)}</p><strong>Prevención</strong><p>${esc(p.prevention)}</p><strong>Control</strong><p>${esc(p.control)}</p></div></section><div class="warning-box">No sustituye una identificación profesional. Para productos fitosanitarios, usa solo productos autorizados para cultivo y problema, y respeta su etiqueta vigente.</div>`)})}

function openMore(a){if(a==='tasks')return openTasksManager();if(a==='zones')return openZones();if(a==='inventory')return openInventory();if(a==='ph')return openPhHistory();if(a==='dose')return openDoseCalc();if(a==='harvests')return openHarvestStats();if(a==='problems')return openProblems();if(a==='search')return openGlobalSearch();if(a==='seasons')return openSeasons();if(a==='backup')return openBackup();if(a==='auth')return openAuth();if(a==='about')return openAbout()}
function openTasksManager(){const arr=state.tasks.filter(t=>!t.done).sort((a,b)=>a.date.localeCompare(b.date));modal('✅ Tareas pendientes',`${arr.length?`<div class="list">${arr.map(taskRow).join('')}</div>`:'<div class="empty">No hay tareas pendientes.</div>'}<button class="btn primary block" id="newTaskMore" style="margin-top:12px">+ Añadir tarea</button>`);$('#newTaskMore').onclick=()=>openTaskForm();$$('[data-complete-task]').forEach(b=>b.onclick=()=>{completeTask(b.dataset.completeTask);openTasksManager()});$$('[data-edit-task]').forEach(b=>b.onclick=()=>editTaskMenu(b.dataset.editTask))}
function openZones(){modal('🗺️ Zonas del huerto',`${state.zones.length?`<div class="list">${state.zones.map(z=>{const hist=state.plantings.filter(p=>p.zoneId===z.id).map(p=>cropInfo(p.cropId).family);const repeat=hist.length>1&&hist[hist.length-1]===hist[hist.length-2];return `<div class="list-item"><div class="grow"><strong>${esc(z.name)}</strong><p>${esc(z.notes||'')}${hist.length?' · Familias: '+esc([...new Set(hist)].join(', ')):''}</p>${repeat?'<span class="badge warn">Revisar rotación</span>':''}</div><button class="icon-btn" data-del-zone="${z.id}" style="width:38px;height:38px">✕</button></div>`}).join('')}</div>`:'<div class="empty">Crea zonas como Bancal 1, Patatas, Invernadero…</div>'}<form id="zoneForm" class="form-grid" style="margin-top:12px"><div class="field"><label>Nombre</label><input name="name" required></div><div class="field"><label>Superficie m²</label><input type="number" step="0.1" name="area"></div><div class="field full"><label>Notas</label><input name="notes"></div><div class="field full"><button class="btn primary">Añadir zona</button></div></form>`);$('#zoneForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.zones.push({id:uid(),...d,area:Number(d.area)||null});saveLocal();openZones();render()};$$('[data-del-zone]').forEach(b=>b.onclick=()=>{state.zones=state.zones.filter(z=>z.id!==b.dataset.delZone);saveLocal();openZones();render()})}
function openInventory(){modal('📦 Mi almacén',`${state.inventory.length?`<div class="list">${state.inventory.map(x=>`<div class="list-item"><div class="grow"><strong>${esc(x.name)}</strong><p>${esc(x.category)} · ${x.quantity||0} ${esc(x.unit||'')} ${x.expiry?`· cad. ${fmtDate(x.expiry)}`:''}</p></div><button class="icon-btn" data-del-inv="${x.id}" style="width:38px;height:38px">✕</button></div>`).join('')}</div>`:'<div class="empty">El almacén está vacío.</div>'}<button class="btn primary block" id="addInventory" style="margin-top:12px">+ Añadir producto</button>`);$('#addInventory').onclick=openInventoryForm;$$('[data-del-inv]').forEach(b=>b.onclick=()=>{state.inventory=state.inventory.filter(x=>x.id!==b.dataset.delInv);saveLocal();openInventory()})}
function openInventoryForm(){modal('Añadir al almacén',`<form id="invForm" class="form-grid"><div class="field full"><label>Nombre</label><input name="name" required></div><div class="field"><label>Categoría</label><select name="category"><option>Fertilizantes</option><option>Fitosanitarios</option><option>Semillas</option><option>Herramientas</option><option>Otros productos</option></select></div><div class="field"><label>Tipo/composición</label><input name="composition"></div><div class="field"><label>Cantidad</label><input type="number" step="0.01" name="quantity"></div><div class="field"><label>Unidad</label><select name="unit"><option>kg</option><option>g</option><option>L</option><option>ml</option><option>ud</option></select></div><div class="field"><label>Fecha compra</label><input type="date" name="purchase"></div><div class="field"><label>Caducidad</label><input type="date" name="expiry"></div><div class="field"><label>Precio €</label><input type="number" step="0.01" name="price"></div><div class="field full"><label>Dosis de etiqueta / fabricante</label><input name="labelDose"></div><div class="field full"><label>Observaciones</label><textarea name="notes"></textarea></div><div class="field full"><button class="btn primary block">Guardar producto</button></div></form>`);$('#invForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.inventory.push({id:uid(),...d,quantity:Number(d.quantity)||0,price:Number(d.price)||null});saveLocal();openInventory();render()}}
function openPhHistory(){const arr=[...state.ph].sort((a,b)=>b.date.localeCompare(a.date));modal('🧫 Historial de pH',`${arr.length?`<div class="list">${arr.map(x=>{const p=plantingById(x.plantingId),c=p?cropInfo(p.cropId):null,z=state.zones.find(z=>z.id===x.zoneId);let badge='';if(c)badge=x.value<c.ph[0]?'<span class="badge warn">Bajo</span>':x.value>c.ph[1]?'<span class="badge danger">Alto</span>':'<span class="badge">Adecuado</span>';return `<div class="list-item"><div class="grow"><strong>${fmtDate(x.date)} → pH ${x.value}</strong><p>${z?esc(z.name):''}${c?' · '+c.icon+' '+c.name:''} ${x.method?'· '+esc(x.method):''}</p></div>${badge}</div>`}).join('')}</div>`:'<div class="empty">Sin mediciones.</div>'}<button class="btn primary block" id="newPh" style="margin-top:12px">+ Medir pH</button>`);$('#newPh').onclick=openPhForm}
function openDoseCalc(){modal('🧮 Calculadora de dosificación',`<form class="form-grid" id="doseForm"><div class="field"><label>Dosis</label><input type="number" step="0.001" id="doseValue" value="4"></div><div class="field"><label>Unidad</label><select id="doseUnit"><option>g/L</option><option>ml/L</option><option>kg/1.000 L</option><option>L/1.000 L</option><option>g/100 L</option><option>ml/100 L</option></select></div><div class="field full"><label>Volumen de agua (L)</label><input type="number" step="0.1" id="doseVolume" value="100"></div><div class="field full"><div class="calc-result" id="doseResult"></div></div></form>`);const calc=()=>{const d=Number($('#doseValue').value)||0,v=Number($('#doseVolume').value)||0,u=$('#doseUnit').value;let n=0,label='';if(u==='g/L'){n=d*v;label='g'}if(u==='ml/L'){n=d*v;label='ml'}if(u==='kg/1.000 L'){n=d*v/1000;label='kg'}if(u==='L/1.000 L'){n=d*v/1000;label='L'}if(u==='g/100 L'){n=d*v/100;label='g'}if(u==='ml/100 L'){n=d*v/100;label='ml'}$('#doseResult').innerHTML=`Necesitas <b>${+n.toFixed(3)} ${label}</b> de producto.`};['#doseValue','#doseVolume','#doseUnit'].forEach(s=>$(s).oninput=calc);calc()}
function openHarvestStats(){const logs=state.logs.filter(l=>l.type==='Cosecha'&&l.season===state.activeSeason),by={};logs.forEach(l=>{by[l.cropId]=(by[l.cropId]||0)+(Number(l.kg)||0)});modal('🧺 Cosechas',Object.keys(by).length?`<div class="list">${Object.entries(by).map(([cid,kg])=>{const c=cropInfo(cid),plants=activePlantings().filter(p=>p.cropId===cid).reduce((s,p)=>s+(Number(p.plants)||0),0),area=activePlantings().filter(p=>p.cropId===cid).reduce((s,p)=>s+(Number(p.area)||0),0);return `<div class="list-item"><div class="grow"><strong>${c.icon} ${c.name} — ${kg.toFixed(2)} kg</strong><p>${plants?`${(kg/plants).toFixed(2)} kg/planta`:''}${plants&&area?' · ':''}${area?`${(kg/area).toFixed(2)} kg/m²`:''}</p></div></div>`}).join('')}</div>`:'<div class="empty">Todavía no hay cosechas registradas esta temporada.</div>')}
function openGlobalSearch(){modal('🔎 Buscador global',`<div class="search-box"><input id="globalQ" placeholder="hojas amarillas tomate"><button class="btn primary" id="globalGo">Buscar</button></div><div id="globalResults" class="section"></div>`);$('#globalGo').onclick=()=>{const q=$('#globalQ').value.toLowerCase().trim(),words=q.split(/\s+/).filter(Boolean);let rows=[];PROBLEMS.forEach(p=>{const txt=[p.name,p.type,p.identify,p.favours,...p.symptoms].join(' ').toLowerCase(),score=words.filter(w=>txt.includes(w)).length;if(score)rows.push({score,html:`<div class="list-item"><div class="grow"><strong>${esc(p.name)}</strong><p>${esc(p.type)} · ${esc(p.identify)}</p></div></div>`})});CROP_CATALOG.forEach(c=>{const txt=[c.name,c.family,c.water,c.fert,...c.plagues,...c.diseases,...c.deficiencies].join(' ').toLowerCase(),score=words.filter(w=>txt.includes(w)).length;if(score)rows.push({score,html:`<div class="list-item"><div class="grow"><strong>${c.icon} ${c.name}</strong><p>pH ${c.ph[0]}–${c.ph[1]} · ${esc(c.water)}</p></div></div>`})});state.logs.forEach(l=>{const txt=[l.summary,l.notes,l.type,l.product,l.target].join(' ').toLowerCase(),score=words.filter(w=>txt.includes(w)).length;if(score)rows.push({score,html:logRow(l)})});rows.sort((a,b)=>b.score-a.score);$('#globalResults').innerHTML=rows.length?`<div class="list">${rows.slice(0,30).map(r=>r.html).join('')}</div>`:'<div class="empty">No hay coincidencias.</div>'}}
function openSeasons(){modal('🗓️ Temporadas',`<div class="list">${state.seasons.map(s=>`<label class="list-item"><input type="radio" name="seasonChoice" value="${esc(s.name)}" ${s.name===state.activeSeason?'checked':''}><div class="grow"><strong>${esc(s.name)}</strong><p>${state.plantings.filter(p=>p.season===s.name).length} plantaciones · ${state.logs.filter(l=>l.season===s.name).length} registros</p></div></label>`).join('')}</div><form id="seasonForm" class="form-grid" style="margin-top:12px"><div class="field"><label>Nueva temporada</label><input name="name" placeholder="Huerto 2027" required></div><div class="field"><label>Año</label><input type="number" name="year" value="${new Date().getFullYear()+1}"></div><div class="field full"><button class="btn primary">Crear temporada</button></div></form>`);$$('[name="seasonChoice"]').forEach(r=>r.onchange=()=>{state.activeSeason=r.value;saveLocal();closeModal();render()});$('#seasonForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.seasons.push({id:uid(),name:d.name,year:Number(d.year)||null});state.activeSeason=d.name;saveLocal();closeModal();render();toast('Nueva temporada creada')}}
function download(name,text,type='application/json'){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function csvEscape(x){const s=String(x??'');return `"${s.replaceAll('"','""')}"`}
function exportCsv(){const cols=['date','type','crop','summary','notes'];const rows=state.logs.map(l=>[l.date,l.type,l.cropId?cropInfo(l.cropId).name:'',l.summary,l.notes||'']);download(`cuaderno-${state.activeSeason.replaceAll(' ','-')}.csv`,[cols.join(','),...rows.map(r=>r.map(csvEscape).join(','))].join('\n'),'text/csv;charset=utf-8')}
function openBackup(){modal('💾 Copia de seguridad',`<div class="card"><strong>Exportar</strong><p class="help">JSON conserva todos los datos y sirve para restaurar. CSV exporta el cuaderno para abrirlo en una hoja de cálculo.</p><div class="actions"><button class="btn primary" id="exportJson">Exportar JSON</button><button class="btn secondary" id="exportCsvBtn">Exportar CSV</button></div></div><div class="card" style="margin-top:12px"><strong>Restaurar JSON</strong><p class="help">Sustituye los datos locales por una copia exportada anteriormente.</p><input type="file" id="importJson" accept="application/json,.json"></div>`);$('#exportJson').onclick=()=>download(`la-huerta-backup-${today()}.json`,JSON.stringify(state,null,2));$('#exportCsvBtn').onclick=exportCsv;$('#importJson').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());state={...DEFAULT_STATE(),...obj};saveLocal();closeModal();render();toast('Copia restaurada')}catch{toast('El archivo no es un JSON válido')}}}
function openAbout(){modal('ℹ️ Información y seguridad',`<div class="card"><strong>Herramienta de gestión, no receta fitosanitaria</strong><p>Las fichas agronómicas son orientativas. La app separa la información general de los datos legales de cada producto.</p><p><b>No se incluyen dosis legales, materias activas autorizadas ni plazos de seguridad inventados.</b> Cuando registres un tratamiento, copia los datos de la etiqueta vigente del producto y comprueba que el uso esté autorizado para cultivo y problema.</p><p><a href="https://servicio.mapa.gob.es/regfiweb" target="_blank" rel="noopener">Consultar Registro oficial de productos fitosanitarios (MAPA)</a></p></div><div class="card" style="margin-top:12px"><strong>Sin Internet</strong><p>La PWA conserva la interfaz en caché. Cuando Firebase esté configurado, Firestore puede mantener una caché local persistente y sincronizar cambios al reconectar.</p></div>`)}

async function initFirebase(){if(!firebaseEnabled){updateAuthStatus('Firebase pendiente: completa firebase-config.js y habilita Email/Password + Firestore.');return}try{
 const [{initializeApp},{getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,setPersistence,browserLocalPersistence},{initializeFirestore,persistentLocalCache,persistentMultipleTabManager,doc,setDoc,getDoc,onSnapshot}]=await Promise.all([
  import('https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js')]);
 const app=initializeApp(firebaseConfig),auth=getAuth(app);await setPersistence(auth,browserLocalPersistence);const db=initializeFirestore(app,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})});
 firebaseCtx={auth,db,user:null,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,save:async s=>{if(!firebaseCtx.user)return;await setDoc(doc(db,'users',firebaseCtx.user.uid,'data','main'),s,{merge:false})}};
 onAuthStateChanged(auth,async user=>{firebaseCtx.user=user;if(user){updateAuthStatus(`Conectado como ${user.email}`);const ref=doc(db,'users',user.uid,'data','main'),snap=await getDoc(ref);if(snap.exists()){remoteLoading=true;state={...DEFAULT_STATE(),...snap.data()};localStorage.setItem(LOCAL_KEY,JSON.stringify(state));remoteLoading=false;render()}else await firebaseCtx.save(state);onSnapshot(ref,s=>{if(s.exists()&&!s.metadata.hasPendingWrites){remoteLoading=true;state={...DEFAULT_STATE(),...s.data()};localStorage.setItem(LOCAL_KEY,JSON.stringify(state));remoteLoading=false;render()}})}else updateAuthStatus('Sin iniciar sesión. Los datos se guardan solo en este dispositivo.')});
 }catch(e){console.error(e);updateAuthStatus(`Firebase no pudo iniciarse: ${e.message}`)}}
function updateAuthStatus(text){const el=$('#authStatus');if(el)el.textContent=text}
function openAuth(){if(!firebaseEnabled)return modal('👤 Cuenta y Firebase',`<div class="warning-box">Primero crea un proyecto Firebase independiente para “La Huerta de la Abuela”, registra una app web, habilita Authentication por Email/Password y Cloud Firestore, y pega su configuración en <b>firebase-config.js</b>.</div><p class="help">Las reglas listas para publicar están en firestore.rules.</p>`);if(firebaseCtx?.user){modal('👤 Cuenta',`<div class="card"><strong>${esc(firebaseCtx.user.email||'Usuario')}</strong><p class="help">Sincronización Firebase activa.</p><button class="btn danger" id="logoutBtn">Cerrar sesión</button></div>`);$('#logoutBtn').onclick=async()=>{await firebaseCtx.signOut(firebaseCtx.auth);closeModal();render()};return}modal('👤 Iniciar sesión',`<form id="authForm" class="form-grid"><div class="field full"><label>Email</label><input type="email" name="email" required></div><div class="field full"><label>Contraseña</label><input type="password" name="password" minlength="6" required></div><div class="field full"><button class="btn primary block" name="mode" value="login">Entrar</button></div><div class="field full"><button class="btn secondary block" name="mode" value="register">Crear cuenta</button></div></form>`);$('#authForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),mode=e.submitter.value;try{if(mode==='register')await firebaseCtx.createUserWithEmailAndPassword(firebaseCtx.auth,d.email,d.password);else await firebaseCtx.signInWithEmailAndPassword(firebaseCtx.auth,d.email,d.password);closeModal();render();toast('Sesión iniciada')}catch(err){toast(err.message)}}}

$('#closeModal').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#fab').onclick=openQuickMenu;$('#searchBtn').onclick=openGlobalSearch;$$('.nav-item').forEach(b=>b.onclick=()=>setRoute(b.dataset.route));document.addEventListener('click',e=>{if(e.target.matches('[data-action="export-csv"]'))exportCsv()});
window.addEventListener('online',()=>{render();toast('Conexión recuperada')});window.addEventListener('offline',()=>{render();toast('Sin conexión: puedes seguir registrando')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
render();initFirebase();
