export const CROP_CATALOG = [
  {id:'potato',name:'Patatas',icon:'🥔',family:'Solanáceas',ph:[5.2,6.5],days:120,planting:'Final de invierno/primavera y final de verano según clima',temp:[7,18,30],spacing:'70–80 cm entre líneas; 25–35 cm entre plantas',depth:'8–12 cm',sun:'Pleno sol',soil:'Suelto, profundo y bien drenado',water:'Moderado; crítico en tuberización y engorde',fert:'Evitar exceso de N; buen aporte de K',harvest:'Cuando la mata amarillea y la piel del tubérculo está firme',yield:'2–4 kg/m² orientativos',calendar:[['Preparación de terreno',-7],['Siembra',0],['Brotación',14],['Primer aporcado',28],['Segundo aporcado',45],['Floración',55],['Engorde',70],['Reducir riego',95],['Cortar riego',105],['Recolección',120]],plagues:['Escarabajo de la patata','Pulgones','Polilla de la patata','Gusanos del suelo','Araña roja'],diseases:['Mildiu','Alternaria','Podredumbres','Virus'],deficiencies:['Potasio','Magnesio','Problemas de pH']},
  {id:'tomato',name:'Tomates',icon:'🍅',family:'Solanáceas',ph:[5.8,6.8],days:140,planting:'Semillero desde final de invierno; trasplante en primavera',temp:[10,22,35],spacing:'70–100 cm entre líneas; 40–60 cm entre plantas',depth:'0,5–1 cm en semillero',sun:'Pleno sol',soil:'Fértil, aireado y con buen drenaje',water:'Regular y uniforme; evitar altibajos',fert:'Demanda alta de K, Ca y Mg desde floración',harvest:'Con color y firmeza propios de la variedad',yield:'3–8 kg/planta orientativos',calendar:[['Semillero',-50],['Trasplante',0],['Entutorado',10],['Primera poda',15],['Floración',25],['Cuajado',40],['Abonado de producción',45],['Inicio de recolección',70]],plagues:['Araña roja','Vasates','Mosca blanca','Trips','Tuta absoluta','Pulgón','Minadores','Orugas'],diseases:['Mildiu','Oídio','Alternaria','Botritis','Fusarium','Verticillium','Virus','Bacteriosis'],deficiencies:['Calcio','Magnesio','Hierro','Potasio','Exceso de agua','Estrés por calor']},
  {id:'cucumber',name:'Pepinos',icon:'🥒',family:'Cucurbitáceas',ph:[5.8,7.0],days:90,planting:'Primavera y verano',temp:[12,24,35],spacing:'100–150 cm entre líneas; 35–60 cm entre plantas',depth:'2–3 cm',sun:'Pleno sol',soil:'Fértil y con buena retención sin encharcar',water:'Frecuente y constante',fert:'Buen aporte de N al inicio y K en producción',harvest:'Antes de que engorde en exceso y amarillee',yield:'3–8 kg/planta orientativos',calendar:[['Siembra/trasplante',0],['Entutorado',12],['Floración',25],['Cuajado',35],['Inicio de recolección',45]],plagues:['Araña roja','Mosca blanca','Trips','Pulgón'],diseases:['Oídio','Mildiu','Podredumbres','Virus'],deficiencies:['Magnesio','Potasio','Exceso de agua']},
  {id:'pepper',name:'Pimientos',icon:'🌶️',family:'Solanáceas',ph:[5.8,6.8],days:150,planting:'Semillero final de invierno; trasplante primavera',temp:[12,24,35],spacing:'70–100 cm entre líneas; 35–50 cm entre plantas',depth:'0,5–1 cm',sun:'Pleno sol',soil:'Fértil, profundo y drenante',water:'Regular; sensible a estrés hídrico en floración y engorde',fert:'K, Ca y Mg importantes en producción',harvest:'Verde o maduro según variedad',yield:'2–5 kg/planta orientativos',calendar:[['Trasplante',0],['Primer abonado',15],['Floración',25],['Cuajado',40],['Abonado de producción',50],['Recolección',70]],plagues:['Araña roja','Trips','Pulgón','Mosca blanca'],diseases:['Oídio','Botritis','Virus','Bacteriosis'],deficiencies:['Calcio','Magnesio','Hierro','Potasio','Estrés por calor']},
  {id:'eggplant',name:'Berenjenas',icon:'🍆',family:'Solanáceas',ph:[5.8,6.8],days:150,planting:'Primavera',temp:[12,25,36],spacing:'80–100 cm entre líneas; 45–60 cm entre plantas',depth:'0,5–1 cm',sun:'Pleno sol',soil:'Fértil y profundo',water:'Regular y abundante en producción',fert:'Alta demanda durante fructificación',harvest:'Fruto brillante y firme, antes de sobremadurar',yield:'3–6 kg/planta orientativos',calendar:[['Trasplante',0],['Tutorado',15],['Floración',30],['Cuajado',45],['Inicio de cosecha',70]],plagues:['Araña roja','Mosca blanca','Trips','Pulgón'],diseases:['Verticillium','Fusarium','Botritis','Oídio'],deficiencies:['Magnesio','Potasio','Hierro']},
  {id:'zucchini',name:'Calabacines',icon:'🥒',family:'Cucurbitáceas',ph:[5.8,7.0],days:70,planting:'Primavera-verano',temp:[10,23,35],spacing:'100–150 cm entre líneas; 70–100 cm entre plantas',depth:'2–3 cm',sun:'Pleno sol',soil:'Fértil y rico en materia orgánica',water:'Frecuente y abundante',fert:'N equilibrado y buen K en producción',harvest:'Joven y tierno, normalmente 15–25 cm',yield:'3–8 kg/planta orientativos',calendar:[['Siembra/trasplante',0],['Floración',25],['Inicio de cosecha',35]],plagues:['Araña roja','Pulgón','Mosca blanca'],diseases:['Oídio','Mildiu','Podredumbres'],deficiencies:['Potasio','Magnesio','Exceso de agua']},
  {id:'broadbean',name:'Habas',icon:'🫘',family:'Leguminosas',ph:[6.0,7.5],days:120,planting:'Otoño-invierno y final de invierno según clima',temp:[4,15,24],spacing:'50–70 cm entre líneas; 20–40 cm entre golpes',depth:'4–6 cm',sun:'Sol',soil:'Profundo y drenante',water:'Moderado; crítico en floración y llenado',fert:'Poco N; aprovecha fijación biológica',harvest:'Vainas llenas antes de endurecer',yield:'1–2,5 kg/m² orientativos',calendar:[['Siembra',0],['Emergencia',10],['Aporcado ligero',30],['Floración',60],['Llenado de vainas',80],['Cosecha',100]],plagues:['Pulgón negro','Sitona','Trips'],diseases:['Roya','Botritis','Mancha chocolate'],deficiencies:['Potasio','Fósforo','Exceso de agua']},
  {id:'bean',name:'Judías',icon:'🫘',family:'Leguminosas',ph:[6.0,7.5],days:80,planting:'Primavera-verano',temp:[10,22,32],spacing:'50–80 cm entre líneas; 15–30 cm entre plantas',depth:'3–5 cm',sun:'Pleno sol',soil:'Ligero y fértil',water:'Regular, sobre todo en floración',fert:'Evitar exceso de N',harvest:'Vaina tierna antes de formar fibra',yield:'1,5–3 kg/m² orientativos',calendar:[['Siembra',0],['Emergencia',8],['Entutorado',15],['Floración',35],['Cosecha',50]],plagues:['Pulgón','Araña roja','Trips'],diseases:['Antracnosis','Roya','Oídio','Virus'],deficiencies:['Magnesio','Potasio']},
  {id:'watermelon',name:'Sandías',icon:'🍉',family:'Cucurbitáceas',ph:[5.8,7.2],days:100,planting:'Primavera',temp:[15,26,38],spacing:'150–250 cm entre líneas; 80–150 cm entre plantas',depth:'2–3 cm',sun:'Pleno sol',soil:'Profundo y drenante',water:'Regular; reducir cerca de maduración',fert:'K importante en engorde y calidad',harvest:'Zarcillo próximo seco, sonido más grave y mancha de apoyo marcada',yield:'3–7 kg/planta orientativos',calendar:[['Trasplante',0],['Floración',30],['Cuajado',40],['Engorde',55],['Reducir riego',80],['Cosecha',90]],plagues:['Pulgón','Araña roja','Trips'],diseases:['Oídio','Fusarium','Mildiu'],deficiencies:['Potasio','Magnesio']},
  {id:'melon',name:'Melones',icon:'🍈',family:'Cucurbitáceas',ph:[6.0,7.2],days:100,planting:'Primavera',temp:[15,25,38],spacing:'150–200 cm entre líneas; 70–120 cm entre plantas',depth:'2–3 cm',sun:'Pleno sol',soil:'Profundo y drenante',water:'Regular; reducir al acercarse maduración',fert:'K importante para calidad',harvest:'Aroma intenso, color y desprendimiento según variedad',yield:'2–5 kg/planta orientativos',calendar:[['Trasplante',0],['Floración',28],['Cuajado',40],['Engorde',55],['Reducir riego',80],['Cosecha',90]],plagues:['Pulgón','Araña roja','Trips'],diseases:['Oídio','Fusarium','Mildiu'],deficiencies:['Potasio','Magnesio']},
  {id:'strawberry',name:'Fresas',icon:'🍓',family:'Rosáceas',ph:[5.5,6.5],days:180,planting:'Otoño o final de invierno',temp:[5,18,30],spacing:'30–40 cm entre líneas; 25–35 cm entre plantas',depth:'Corona a ras de suelo',sun:'Sol',soil:'Rico en materia orgánica y ligeramente ácido',water:'Frecuente sin encharcar',fert:'Equilibrado; K en floración y fruto',harvest:'Rojo uniforme y aromático',yield:'0,4–1 kg/planta orientativos',calendar:[['Plantación',0],['Enraizamiento',20],['Floración',50],['Cosecha',70]],plagues:['Araña roja','Trips','Pulgón'],diseases:['Botritis','Oídio','Podredumbres'],deficiencies:['Hierro','Magnesio','Problemas de pH']},
  {id:'lettuce',name:'Lechugas',icon:'🥬',family:'Compuestas',ph:[6.0,7.0],days:60,planting:'Gran parte del año según variedad',temp:[4,16,28],spacing:'30–40 cm entre líneas; 25–35 cm entre plantas',depth:'0,5 cm',sun:'Sol o semisombra en calor',soil:'Fértil y fresco',water:'Frecuente y suave',fert:'N moderado, evitar exceso',harvest:'Cabeza formada y tierna',yield:'2–4 kg/m² orientativos',calendar:[['Siembra/trasplante',0],['Crecimiento',20],['Cosecha',45]],plagues:['Pulgón','Babosas','Minadores'],diseases:['Mildiu','Botritis','Podredumbres'],deficiencies:['Nitrógeno','Exceso de agua']},
  {id:'chard',name:'Acelgas',icon:'🥬',family:'Amarantáceas',ph:[6.0,7.5],days:70,planting:'Primavera y otoño',temp:[5,18,30],spacing:'40–60 cm entre líneas; 25–40 cm entre plantas',depth:'2–3 cm',sun:'Sol o semisombra',soil:'Fértil y fresco',water:'Regular',fert:'N moderado',harvest:'Cortar hojas exteriores tiernas',yield:'2–5 kg/m² orientativos',calendar:[['Siembra',0],['Aclareo',15],['Primer corte',45]],plagues:['Pulgón','Minadores'],diseases:['Cercospora','Mildiu'],deficiencies:['Nitrógeno','Magnesio']},
  {id:'spinach',name:'Espinacas',icon:'🥬',family:'Amarantáceas',ph:[6.0,7.5],days:50,planting:'Otoño-invierno y primavera fresca',temp:[2,15,25],spacing:'25–35 cm entre líneas; 8–15 cm entre plantas',depth:'2–3 cm',sun:'Sol o semisombra',soil:'Fértil y fresco',water:'Regular',fert:'N moderado',harvest:'Hojas desarrolladas antes de espigar',yield:'1,5–3 kg/m² orientativos',calendar:[['Siembra',0],['Aclareo',12],['Cosecha',35]],plagues:['Pulgón','Minadores'],diseases:['Mildiu','Podredumbres'],deficiencies:['Nitrógeno','Magnesio']},
  {id:'onion',name:'Cebollas',icon:'🧅',family:'Allium',ph:[6.0,7.0],days:150,planting:'Otoño o final de invierno según variedad',temp:[3,18,30],spacing:'30–40 cm entre líneas; 10–15 cm entre plantas',depth:'1–2 cm',sun:'Pleno sol',soil:'Suelto y drenante',water:'Regular; reducir al madurar',fert:'N moderado al inicio; K en engorde',harvest:'Cuando el cuello se ablanda y las hojas se tumban',yield:'3–6 kg/m² orientativos',calendar:[['Plantación',0],['Crecimiento',30],['Engorde de bulbo',80],['Reducir riego',120],['Cosecha',140]],plagues:['Trips','Mosca de la cebolla'],diseases:['Mildiu','Botritis','Podredumbres'],deficiencies:['Nitrógeno','Potasio']},
  {id:'garlic',name:'Ajos',icon:'🧄',family:'Allium',ph:[6.0,7.5],days:210,planting:'Otoño-invierno',temp:[0,15,30],spacing:'30–40 cm entre líneas; 10–15 cm entre dientes',depth:'3–5 cm',sun:'Pleno sol',soil:'Suelto y drenante',water:'Moderado; evitar exceso al final',fert:'Moderado; no abusar de N',harvest:'Cuando se seca aproximadamente la mitad de las hojas',yield:'0,8–2 kg/m² orientativos',calendar:[['Plantación',0],['Brotación',15],['Engorde de bulbo',120],['Reducir riego',170],['Cosecha',190]],plagues:['Trips','Mosca de la cebolla'],diseases:['Roya','Podredumbre blanca'],deficiencies:['Nitrógeno','Potasio']},
  {id:'carrot',name:'Zanahorias',icon:'🥕',family:'Umbelíferas',ph:[6.0,7.0],days:100,planting:'Otoño, invierno suave y primavera',temp:[5,18,28],spacing:'25–35 cm entre líneas; 4–8 cm entre plantas',depth:'0,5–1,5 cm',sun:'Sol',soil:'Muy suelto, sin piedras',water:'Regular y uniforme',fert:'Evitar estiércol fresco y exceso de N',harvest:'Cuando la raíz alcanza calibre adecuado',yield:'3–6 kg/m² orientativos',calendar:[['Siembra',0],['Emergencia',12],['Aclareo',25],['Engorde',55],['Cosecha',90]],plagues:['Mosca de la zanahoria','Pulgón'],diseases:['Alternaria','Oídio'],deficiencies:['Potasio','Problemas de suelo']},
  {id:'pumpkin',name:'Calabazas',icon:'🎃',family:'Cucurbitáceas',ph:[5.8,7.2],days:130,planting:'Primavera',temp:[12,24,36],spacing:'150–250 cm entre líneas; 100–200 cm entre plantas',depth:'3–4 cm',sun:'Pleno sol',soil:'Rico y profundo',water:'Abundante sin mojar continuamente hojas',fert:'Buena disponibilidad de N y K',harvest:'Pedúnculo endurecido y piel que resiste la uña',yield:'5–15 kg/planta orientativos',calendar:[['Siembra/trasplante',0],['Floración',35],['Cuajado',50],['Engorde',70],['Cosecha',110]],plagues:['Araña roja','Pulgón'],diseases:['Oídio','Mildiu','Podredumbres'],deficiencies:['Potasio','Magnesio']},
  {id:'corn',name:'Maíz',icon:'🌽',family:'Gramíneas',ph:[5.8,7.2],days:110,planting:'Primavera-verano',temp:[10,24,35],spacing:'60–80 cm entre líneas; 20–30 cm entre plantas',depth:'3–5 cm',sun:'Pleno sol',soil:'Profundo y fértil',water:'Alto en crecimiento, floración y llenado',fert:'Demanda alta de N y K',harvest:'Grano lechoso para mazorca tierna',yield:'1–2 mazorcas/planta orientativas',calendar:[['Siembra',0],['Emergencia',7],['Crecimiento rápido',30],['Floración',55],['Llenado',70],['Cosecha',90]],plagues:['Taladros','Pulgón','Gusanos del suelo'],diseases:['Carbón','Fusariosis'],deficiencies:['Nitrógeno','Potasio','Fósforo']}
];

export const NUTRIENTS = [
  ['Nitrógeno','Impulsa hojas y crecimiento. Falta: amarilleo general empezando en hojas viejas. Exceso: mucha hoja, tejidos blandos y peor fructificación.'],
  ['Fósforo','Favorece raíces, floración y energía. Falta: crecimiento lento y tonos verde oscuro o violáceos, sobre todo con frío.'],
  ['Potasio','Regula agua, resistencia y calidad de fruto. Falta: bordes secos o quemados en hojas viejas y peor llenado.'],
  ['Calcio','Clave en paredes celulares y tejidos jóvenes. Falta: necrosis en brotes o frutos; en tomate/pimiento puede aparecer podredumbre apical.'],
  ['Magnesio','Forma parte de la clorofila. Falta: amarilleo entre nervios de hojas viejas manteniendo nervios más verdes.'],
  ['Hierro','Necesario para formar clorofila. Falta: hojas jóvenes amarillas con nervios relativamente verdes; frecuente con pH alto.'],
  ['Micronutrientes','Boro, manganeso, zinc, cobre y otros se necesitan en poca cantidad. Evita suplementarlos sin causa clara porque el exceso también puede dañar.']
];

export const PROBLEMS = [
  {name:'Araña roja',type:'Plaga',symptoms:['puntos claros','hojas amarillas','telarañas','planta debilitada'],favours:'Calor y ambiente seco',identify:'Punteado fino, aspecto bronceado y, en ataques fuertes, telarañas en el envés.',prevention:'Evitar estrés hídrico, revisar envés y favorecer fauna auxiliar.',control:'Retirar focos muy dañados y aplicar únicamente productos autorizados siguiendo etiqueta cuando sea necesario.'},
  {name:'Vasates',type:'Plaga',symptoms:['bronceado','hojas enrolladas','tallos dañados','planta debilitada'],favours:'Temperaturas cálidas',identify:'Bronceado o aspecto corchoso progresivo en tallos y hojas de tomate; ácaro microscópico.',prevention:'Inspección frecuente y evitar dispersar material vegetal infestado.',control:'Confirmar antes de tratar; usar únicamente soluciones autorizadas y según etiqueta.'},
  {name:'Mosca blanca',type:'Plaga',symptoms:['hojas amarillas','melaza','planta debilitada'],favours:'Tiempo cálido y ambientes protegidos',identify:'Adultos blancos que vuelan al mover la planta; ninfas en envés.',prevention:'Control de malas hierbas, trampas de seguimiento y fauna auxiliar.',control:'Medidas físicas/biológicas y fitosanitarios autorizados cuando proceda.'},
  {name:'Trips',type:'Plaga',symptoms:['puntos','manchas plateadas','frutos dañados'],favours:'Calor y sequedad',identify:'Pequeños insectos alargados y raspaduras plateadas.',prevention:'Revisión de flores y malas hierbas, favorecer auxiliares.',control:'Solo productos autorizados y respetando etiqueta.'},
  {name:'Pulgón',type:'Plaga',symptoms:['hojas enrolladas','melaza','planta debilitada'],favours:'Brotes tiernos y temperaturas suaves',identify:'Colonias visibles en brotes y envés; posible presencia de hormigas.',prevention:'Evitar exceso de nitrógeno y favorecer auxiliares.',control:'Agua a presión en focos, retirada localizada y productos autorizados si procede.'},
  {name:'Mildiu',type:'Enfermedad',symptoms:['manchas','hojas amarillas','necrosis'],favours:'Humedad alta, mojado foliar prolongado y temperaturas suaves',identify:'Manchas que avanzan rápido; en varias especies puede aparecer esporulación en envés.',prevention:'Ventilación, riego al suelo, espaciamiento y retirada de restos afectados.',control:'Manejo preventivo y productos legalmente autorizados según cultivo y etiqueta.'},
  {name:'Oídio',type:'Enfermedad',symptoms:['polvo blanco','manchas','hojas debilitadas'],favours:'Temperaturas templadas-cálidas y humedad ambiental sin necesidad de hoja mojada',identify:'Polvillo blanco superficial en hojas y tallos.',prevention:'Ventilación, evitar exceso de vigor y vigilar desde los primeros focos.',control:'Retirar focos y usar tratamientos autorizados cuando proceda.'},
  {name:'Alternaria',type:'Enfermedad',symptoms:['manchas oscuras','anillos concéntricos','hojas amarillas'],favours:'Humedad y tejido debilitado',identify:'Manchas marrones con aspecto de diana en muchas especies.',prevention:'Rotación, restos sanos y evitar mojar hojas.',control:'Confirmar el problema y aplicar manejo/fitosanitarios autorizados.'},
  {name:'Botritis',type:'Enfermedad',symptoms:['podredumbre','moho gris','frutos dañados'],favours:'Humedad elevada y mala ventilación',identify:'Podredumbre blanda y moho gris característico.',prevention:'Ventilar, retirar tejido muerto y evitar heridas/agua sobre órganos sensibles.',control:'Saneamiento y productos autorizados si fueran necesarios.'},
  {name:'Falta de nitrógeno',type:'Carencia',symptoms:['hojas amarillas','crecimiento lento'],favours:'Baja disponibilidad de N o raíces poco activas',identify:'Amarilleo relativamente uniforme que suele empezar en hojas viejas.',prevention:'Plan de fertilización equilibrado.',control:'Corregir solo tras valorar riego, raíces, pH y abonado reciente.'},
  {name:'Falta de magnesio',type:'Carencia',symptoms:['hojas amarillas','nervios verdes','manchas'],favours:'Desequilibrios K/Mg, suelos pobres o raíces limitadas',identify:'Clorosis entre nervios de hojas viejas.',prevention:'Fertilización equilibrada y pH adecuado.',control:'Confirmar antes de aportar Mg; seguir dosis del producto.'},
  {name:'Falta de hierro',type:'Carencia',symptoms:['hojas amarillas','nervios verdes'],favours:'pH alto, exceso de carbonatos o raíces dañadas',identify:'Clorosis entre nervios que aparece primero en hojas jóvenes.',prevention:'Mantener pH compatible y buen funcionamiento radicular.',control:'Corregir la causa; emplear quelatos adecuados siguiendo etiqueta cuando proceda.'},
  {name:'Exceso de agua',type:'Manejo',symptoms:['hojas amarillas','marchitez','planta debilitada'],favours:'Riegos demasiado frecuentes o mal drenaje',identify:'Suelo persistentemente húmedo, raíces con poco oxígeno y crecimiento parado.',prevention:'Ajustar frecuencia y asegurar drenaje.',control:'Espaciar riegos y resolver encharcamiento.'},
  {name:'Falta de agua',type:'Manejo',symptoms:['marchitez','hojas secas','frutos pequeños'],favours:'Calor, viento, baja reserva de suelo',identify:'Marchitez con suelo seco y recuperación parcial al regar.',prevention:'Riego uniforme y acolchado.',control:'Rehidratar sin pasar bruscamente a exceso.'},
  {name:'Estrés por calor',type:'Manejo',symptoms:['flores caídas','hojas enrolladas','frutos pequeños'],favours:'Temperaturas extremas y radiación intensa',identify:'Problemas coincidentes con episodios de mucho calor sin signos claros de patógeno.',prevention:'Riego uniforme, sombreo puntual cuando sea viable y manejo del follaje.',control:'Reducir estrés, no sobrefertilizar durante el episodio.'},
  {name:'Problemas de pH',type:'Suelo',symptoms:['clorosis','carencias múltiples','crecimiento lento'],favours:'pH fuera del rango del cultivo',identify:'Carencias repetidas pese a que el suelo pueda contener nutrientes.',prevention:'Medir pH de forma consistente y corregir gradualmente.',control:'Ajustar enmiendas con prudencia; evitar correcciones fuertes sin análisis.'}
];

export const ROTATION_FAMILIES = ['Solanáceas','Cucurbitáceas','Leguminosas','Crucíferas','Allium','Umbelíferas','Compuestas','Amarantáceas','Gramíneas','Rosáceas','Otras'];

export const QUICK_ACTIONS = [
  ['irrigation','💧','Registrar riego'],['fertilization','🌱','Registrar abonado'],['treatment','🧪','Registrar tratamiento'],['harvest','🧺','Registrar cosecha'],['task','✅','Añadir tarea'],['observation','📝','Añadir observación'],['crop','🌿','Añadir cultivo'],['ph','🧫','Medir pH']
];
